/** Lao UI strings for the entire application */
export const lo = {
  common: {
    loading: 'ກຳລັງໂຫຼດ…',
    save: 'ບັນທຶກ',
    saving: 'ກຳລັງບັນທຶກ…',
    cancel: 'ຍົກເລີກ',
    delete: 'ລຶບ',
    edit: 'ແກ້ໄຂ',
    add: 'ເພີ່ມ',
    search: 'ຄົ້ນຫາ',
    required: 'ຈຳເປັນຕ້ອງປ້ອນ',
    na: '—',
    product: 'ສິນຄ້າ',
    free: 'ຟຣີ',
    total: 'ລວມ',
    actions: 'ຈັດການ',
    status: 'ສະຖານະ',
    date: 'ວັນທີ',
    name: 'ຊື່',
    email: 'ອີເມວ',
    tel: 'ເບີໂທ',
    address: 'ທີ່ຢູ່',
    password: 'ລະຫັດຜ່ານ',
    username: 'ຊື່ຜູ້ໃຊ້',
    quantity: 'ຈຳນວນ',
    price: 'ລາຄາ',
    qty: 'ຈຳນວນ',
    backToShop: 'ກັບໄປຮ້ານຄ້າ',
    goHome: 'ກັບໜ້າຫຼັກ',
    viewAll: 'ເບິ່ງທັງໝົດ',
    noData: 'ບໍ່ມີຂໍ້ມູນ',
    confirm: 'ຢືນຢັນ',
    send: 'ສົ່ງ',
    sending: 'ກຳລັງສົ່ງ…',
    import: 'ນຳເຂົ້າ',
    importing: 'ກຳລັງນຳເຂົ້າ…',
    print: 'ພິມ',
    select: 'ເລືອກ',
    all: 'ທັງໝົດ',
    active: 'ໃຊ້ງານ',
    inactive: 'ບໍ່ໃຊ້ງານ',
    staff: 'ພະນັກງານ',
    admin: 'ຜູ້ດູແລ',
    other: 'ອື່ນໆ',
    uncategorized: 'ບໍ່ມີປະເພດ',
    categoryFallback: 'ປະເພດ',
    requestFailed: 'ຄຳຂໍບໍ່ສຳເລັດ',
    productCount: (n: number) => (n === 1 ? 'ສິນຄ້າ' : 'ສິນຄ້າ'),
  },
  brand: {
    sport: 'SPORT',
    shop: 'SHOP',
    sportShop: 'ຮ້ານກິລາ SportShop',
  },
  nav: {
    home: 'ໜ້າຫຼັກ',
    shop: 'ຮ້ານຄ້າ',
    categories: 'ປະເພດ',
    brands: 'ແບຣນດ໌',
    contact: 'ຕິດຕໍ່',
    login: 'ເຂົ້າສູ່ລະບົບ',
    register: 'ລົງທະບຽນ',
    menu: 'ເມນູ',
  },
  footer: {
    tagline: 'ອຸປະກອນກິລາສຳລັບນັກກິລາທີ່ບໍ່ຍອມຫຍຸດ. ສິນຄ້າແທ້, ຈັດສົ່ງໄວ.',
    shop: 'ຮ້ານຄ້າ',
    company: 'ບໂລກສ໌',
    allProducts: 'ສິນຄ້າທັງໝົດ',
    aboutUs: 'ກ່ຽວກັບພວກເຮົາ',
    privacy: 'ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ',
    copyright: '© 2026 SportShop. ສະຫງວນລິຂະສິດ.',
  },
  adminNav: {
    panel: 'ແຜງຄວບຄຸມ',
    dashboard: 'ແຜງສະຫຼຸບ',
    products: 'ສິນຄ້າ',
    categories: 'ປະເພດ',
    brands: 'ແບຣນດ໌',
    suppliers: 'ຜູ້ສະໜອງ',
    customers: 'ລູກຄ້າ',
    users: 'ຜູ້ໃຊ້',
    orders: 'ຄຳສັ່ງຊື້',
    imports: 'ນຳເຂົ້າສິນຄ້າ',
    logout: 'ອອກຈາກລະບົບ',
    signIn: 'ເຂົ້າສູ່ລະບົບ',
    adminPanel: 'ແຜງຄວບຄຸມຜູ້ດູແລ',
  },
  auth: {
    login: 'ເຂົ້າສູ່ລະບົບ',
    signingIn: 'ກຳລັງເຂົ້າສູ່ລະບົບ…',
    createAccount: 'ສ້າງບັນຊີ',
    creatingAccount: 'ກຳລັງສ້າງບັນຊີ…',
    fullName: 'ຊື່ເຕັມ',
    surname: 'ນາມສະກຸນ',
    dateOfBirth: 'ວັນເດືອນປີເກີດ',
    telephone: 'ເບີໂທ',
    noAccount: 'ຍັງບໍ່ມີບັນຊີ?',
    haveAccount: 'ມີບັນຊີແລ້ວ?',
    welcomeBack: 'ຍິນດີຕ້ອນຮັບກັບຄືນ!',
    accountCreated: 'ສ້າງບັນຊີສຳເລັດ! ກະລຸນາເຂົ້າສູ່ລະບົບ.',
    loginFailed: 'ເຂົ້າສູ່ລະບົບບໍ່ສຳເລັດ',
    registerFailed: 'ລົງທະບຽນບໍ່ສຳເລັດ',
  },
  notFound: {
    title: '404',
    heading: 'ບໍ່ພົບໜ້ານີ້',
    body: 'ໜ້າທີ່ທ່ານຊອກຫາບໍ່ມີຢູ່ ຫຼື ຖືກຍ້າຍແລ້ວ.',
  },
  home: {
    badge: 'ລະດູໃໝ່ · 2026',
    headline1: 'ເຮັດໃຫ້',
    headline2: 'ຫຼາຍຂຶ້ນ.',
    heroBody:
      'ອຸປະກອນກິລາສຳລັບນັກກິລາທີ່ບໍ່ຍອມຫຍຸດ. ຝຶກຫນັກ, ວິ่งໄວ, ເລ່ນດີ.',
    shopNow: 'ຊື້ເລີຍ',
    explore: 'ສຳຫຼວດ',
    athleteAlt: 'ນັກກິລາກຳລັງວິ่ง',
    freeShipping: 'ຈັດສົ່ງຟຣີ',
    freeShippingSub: 'ສັ່ງຊື້ເກີນ ฿5,000',
    authentic: 'ສິນຄ້າແທ້ 100%',
    authenticSub: 'ຮັບປະກັນຂອງແທ້',
    easyReturns: 'ຄືນສິນຄ້າງ່າຍ',
    easyReturnsSub: 'ຄືນໄດ້ 30 ວັນ',
    support: 'ຊ່ວຍເຫຼືອ 24/7',
    supportSub: 'ພ້ອມໃຫ້ບໍລິການສະເໝີ',
    shopBySport: 'ຊອບຕາມກິລາ',
    chooseGame: 'ເລືອກກິລາຂອງທ່ານ',
    noCategories: 'ບໍ່ມີປະເພດ.',
    featured: 'ແນະນຳ',
    hotRightNow: 'ຮ້ອນແຮງຕອນນີ້',
    shopAll: 'ຊື້ທັງໝົດ',
    noProducts: 'ບໍ່ມີສິນຄ້າ.',
    limitedTime: 'ຈຳກັດເວລາ',
    flash: 'ແຟລດ',
    sale: 'ລົດລາຄາ',
    flashBody: 'ລາຄາພິເສດສຳລັບສິນຄ້າມີສະຕ໋ອກ. ໝົດແລ້ວໝົດເລີຍ.',
    shopDeals: 'ຊື້ລາຄາພິເສດ',
    noSaleItems: 'ບໍ່ມີສິນຄ້າລົດລາຄາຕອນນີ້.',
    bestSellers: 'ຂາຍດີ',
    championPicks: 'ສິນຄ້າຂາຍດີ',
    trustedBy: 'ໄດ້ຮັບຄວາມໄວ້ວາງໃຈ',
    popularBrands: 'ແບຣນດ໌ຍອດນິຍົມ',
    noBrands: 'ບໍ່ມີແບຣນດ໌.',
    fastDelivery: 'ຈັດສົ່ງໄວ',
    shopConfidence: 'ຊື້ສິນຄ້າດ້ວຍຄວາມໝັ້ນໃຈ.',
    browseApi:
      'ສຳຫຼວດສິນຄ້າ, ປະເພດ ແລະ ແບຣນດ໌ຈາກຮ້ານຂອງພວກເຮົາ.',
    qualityGear: 'ອຸປະກອນຄຸນນະພາບ',
    qualityBody:
      'ສິນຄ້າກິລາຄັດສັນສຳລັບການຝຶກຊ້ຳ ແລະ ແຂ່ງຂັນ.',
    simpleNav: 'ນຳທາງງ່າຍ',
    simpleNavBody:
      'ສຳຫຼວດຮ້ານ, ເພີ່ມໃສ່ກະຕ່າ ແລະ ຊຳລະດ້ວຍສະຕ໋ອກຈິງ.',
  },
  shop: {
    title: 'ຊື້ທັງໝົດ',
    searchPlaceholder: 'ຄົ້ນຫາສິນຄ້າ...',
    category: 'ປະເພດ',
    allCategories: 'ທຸກປະເພດ',
    brand: 'ແບຣນດ໌',
    allBrands: 'ທຸກແບຣນດ໌',
    maxPrice: (n: number) => `ລາຄາສູງສຸດ: ฿${n}`,
    resetFilters: 'ລີເຊັດຕົວກອງ',
    sortFeatured: 'ແນະນຳ',
    sortPriceLow: 'ລາຄາ: ຕ່ຳ → ສູງ',
    sortPriceHigh: 'ລາຄາ: ສູງ → ຕ່ຳ',
    sortName: 'ຊື່ ກ-ຮ',
    loadingProducts: 'ກຳລັງໂຫຼດສິນຄ້າ…',
    showing: (n: number, m: number) => `ສະແດງ ${n} ຈາກ ${m}`,
    noMatch: 'ບໍ່ມີສິນຄ້າຕາມຕົວກອງ.',
    products: (n: number) => `${n} ສິນຄ້າ`,
  },
  category: {
    allTitle: 'ທຸກປະເພດ',
    loading: 'ກຳລັງໂຫຼດປະເພດ…',
    notFound: 'ບໍ່ພົບປະເພດ',
    loadingOne: 'ກຳລັງໂຫຼດປະເພດ…',
    label: 'ປະເພດ',
    noProducts: 'ຍັງບໍ່ມີສິນຄ້າໃນປະເພດນີ້.',
  },
  brandPage: {
    title: 'ແບຣນດ໌ຍອດນິຍົມ',
    loading: 'ກຳລັງໂຫຼດແບຣນດ໌…',
    noBrands: 'ບໍ່ມີແບຣນດ໌.',
  },
  contact: {
    label: 'ຕິດຕໍ່',
    title: 'ຕິດຕໍ່ພວກເຮົາ',
    body: 'ມີຄຳຖາມກ່ຽວກັບອຸປະກອນ, ຂະໜາດ ຫຼື ຄຳສັ່ງຊື້? ທີມງານພ້ອມຊ່ວຍເຫຼືອ.',
    message: 'ຂໍ້ຄວາມ',
    nameRequired: 'ກະລຸນາປ້ອນຊື່',
    emailInvalid: 'ກະລຸນາປ້ອນອີເມວທີ່ຖືກຕ້ອງ',
    messageRequired: 'ກະລຸນາປ້ອນຂໍ້ຄວາມ',
    sent: 'ສົ່ງຂໍ້ຄວາມສຳເລັດ',
  },
  cart: {
    loading: 'ກຳລັງໂຫຼດກະຕ່າ…',
    emptyTitle: 'ກະຕ່າຂອງທ່ານວ່າງ',
    emptyBody: 'ເພີ່ມສິນຄ້າແລ້ວກັບມາ.',
    shopNow: 'ຊື້ເລີຍ',
    title: 'ກະຕ່າຂອງທ່ານ',
    noValid: 'ບໍ່ມີສິນຄ້າທີ່ຖືກຕ້ອງໃນກະຕ່າ.',
    size: 'ຂະໜາດ:',
    color: 'ສີ:',
    orderSummary: 'ສະຫຼຸບຄຳສັ່ງຊື້',
    subtotal: 'ລວມຍ່ອຍ',
    shipping: 'ຄ່າຈັດສົ່ງ',
    freeShippingHint: (amount: string) => `ເພີ່ມອີກ ${amount} ເພື່ອຈັດສົ່ງຟຣີ`,
    checkout: 'ຊຳລະເງິນ',
  },
  checkout: {
    loading: 'ກຳລັງໂຫຼດການຊຳລະ…',
    emptyCart: 'ກະຕ່າຂອງທ່ານວ່າງ',
    continueShopping: 'ຊື້ສິນຄ້າຕໍ່',
    orderCancelled: 'ຍົກເລີກຄຳສັ່ງຊື້ແລ້ວ',
    orderStatus: 'ສະຖານະຄຳສັ່ງຊື້',
    qrPayment: 'ຊຳລະ QR',
    orderNo: 'ຄຳສັ່ງຊື້ #',
    payment: 'ການຊຳລະ',
    shipping: 'ການຈັດສົ່ງ',
    cancelledTitle: 'ຍົກເລີກຄຳສັ່ງຊື້ແລ້ວ',
    cancelledBody: 'ຄຳສັ່ງຊື້ນີ້ຖືກຍົກເລີກແລ້ວ',
    backToOrders: 'ກັບໄປຄຳສັ່ງຊື້',
    scanToPay: 'ສະແກນເພື່ອຊຳລະ',
    qrHint: 'ໂອນເງິນຜ່ານ LAO QR / LAPNet ແລ້ວອັບໂຫຼດໃບຮັບເງິນດ້ານລຸ່ມ.',
    qrAlt: 'QR ຊຳລະເງິນ',
    amountToPay: 'ຈຳນວນເງິນທີ່ຕ້ອງຊຳລະ',
    uploadReceipt: 'ອັບໂຫຼດໃບຮັບເງິນ',
    uploading: 'ກຳລັງອັບໂຫຼດ…',
    confirmPayment: 'ຢືນຢັນການຊຳລະ',
    cancelling: 'ກຳລັງຍົກເລີກ…',
    cancelOrder: 'ຍົກເລີກຄຳສັ່ງຊື້',
    viewOrders: 'ເບິ່ງຄຳສັ່ງຊື້',
    paymentSuccess: 'ຊຳລະສຳເລັດ',
    paymentSuccessBody: 'ລະບົບໄດ້ຮັບການຊຳລະເງິນຂອງທ່ານແລ້ວ ກຳລັງກວດສອບ',
    title: 'ຊຳລະເງິນ',
    customerInfo: 'ຂໍ້ມູນລູກຄ້າ',
    shippingAddress: 'ທີ່ຢູ່ຈັດສົ່ງ',
    paymentMethod: 'ວິທີຊຳລະ',
    orderSummary: 'ສະຫຼຸບຄຳສັ່ງຊື້',
    fullName: 'ຊື່ເຕັມ',
    city: 'ເມືອງ',
    postalCode: 'ລະຫັດໄປສະນີ',
    qrMethod: 'ຊຳລະ QR',
    qrMethodHint: 'ສະແກນ QR ເພື່ອຊຳລະທັນທີຜ່ານ LAO QR / LAPNet',
    qrHelp:
      'ຫຼັງສັ່ງຊື້ ລະບົບຈະສະແດງ QR ຈາກເຊີບເວີ ໃຫ້ທ່ານສະແກນ ແລະ ຊຳລະເງິນ.',
    placingOrder: 'ກຳລັງສັ່ງຊື້…',
    placeOrder: 'ສັ່ງຊື້',
    loginRequired: 'ກະລຸນາເຂົ້າສູ່ລະບົບເພື່ອຊຳລະ',
    noValidCart: 'ບໍ່ມີສິນຄ້າທີ່ຖືກຕ້ອງໃນກະຕ່າ',
    orderPlaced: (id: number) => `ສັ່ງຊື້ #${id} ສຳເລັດ! ສະແກນ QR ເພື່ອຊຳລະ.`,
    selectReceipt: 'ກະລຸນາເລືອກຮູບໃບຮັບເງິນ',
    cancelConfirm: (id: number) => `ຍົກເລີກຄຳສັ່ງຊື້ #${id}?`,
    cancelSuccess: 'ຍົກເລີກຄຳສັ່ງຊື້ສຳເລັດ',
    paymentUploaded: 'ອັບໂຫຼດໃບຮັບເງິນສຳເລັດ',
  },
  profile: {
    title: 'ໂປຣໄຟລ໌ຂອງຂ້ອຍ',
    information: 'ຂໍ້ມູນ',
    address: 'ທີ່ຢູ່',
    orders: 'ຄຳສັ່ງຊື້',
    password: 'ລະຫັດຜ່ານ',
    logout: 'ອອກຈາກລະບົບ',
    profileInfo: 'ຂໍ້ມູນໂປຣໄຟລ໌',
    orderHistory: 'ປະຫວັດຄຳສັ່ງຊື້',
    changePassword: 'ປ່ຽນລະຫັດຜ່ານ',
    fullName: 'ຊື່ເຕັມ',
    status: 'ສະຖານະ:',
    loadingOrders: 'ກຳລັງໂຫຼດຄຳສັ່ງຊື້…',
    noOrders: 'ຍັງບໍ່ມີຄຳສັ່ງຊື້.',
    startShopping: 'ເລີ່ມຊື້ສິນຄ້າ',
    items: 'ລາຍການ',
    payNow: 'ຊຳລະເລີຍ',
    newPassword: 'ລະຫັດຜ່ານໃໝ່',
    confirmPassword: 'ຢືນຢັນລະຫັດຜ່ານ',
    updating: 'ກຳລັງອັບເດດ…',
    update: 'ອັບເດດ',
    passwordMin: 'ລະຫັດຜ່ານຕ້ອງມີຢ່າງໜ້ອຍ 4 ຕົວອັກສອນ',
    passwordMismatch: 'ລະຫັດຜ່ານບໍ່ກົງກັນ',
    passwordUpdated: 'ອັບເດດລະຫັດຜ່ານສຳເລັດ',
  },
  product: {
    notFound: 'ບໍ່ພົບສິນຄ້າ',
    loading: 'ກຳລັງໂຫຼດສິນຄ້າ…',
    inStock: (n: number) => `ມີສະຕ໋ອກ (${n} ຊິ້ນ)`,
    outOfStock: 'ສິນຄ້າໝົດ',
    size: 'ຂະໜາດ',
    color: 'ສີ',
    addToCart: 'ເພີ່ມໃສ່ກະຕ່າ',
    buyNow: 'ຊື້ເລີຍ',
    freeShipping: 'ຈັດສົ່ງຟຣີເກີນ ฿5,000',
    authentic: 'ສິນຄ້າແທ້ 100%',
    returns: 'ຄືນໄດ້ 30 ວັນ',
    related: 'ສິນຄ້າທີ່ກ່ຽວຂ້ອງ',
    selectSize: 'ກະລຸນາເລືອກຂະໜາດ',
    selectColor: 'ກະລຸນາເລືອກສີ',
    addedToCart: 'ເພີ່ມໃສ່ກະຕ່າແລ້ວ',
    outOfStockBadge: 'ສິນຄ້າໝົດ',
    inStockShort: (n: number) => `${n} ຊິ້ນ`,
    viewProduct: 'ເບິ່ງສິນຄ້າ',
    editProduct: 'ແກ້ໄຂສິນຄ້າ',
    addProduct: 'ເພີ່ມສິນຄ້າ',
    brand: 'ແບຣນດ໌',
    category: 'ປະເພດ',
    image: 'ຮູບພາບ',
    description: 'ລາຍລະອຽດ',
    loadingBrands: 'ກຳລັງໂຫຼດແບຣນດ໌…',
    selectBrand: 'ເລືອກແບຣນດ໌',
    loadingCategories: 'ກຳລັງໂຫຼດປະເພດ…',
    selectCategory: 'ເລືອກປະເພດ',
    preview: 'ຕົວຢ່າງ',
    selectBrandCategory: 'ກະລຸນາເລືອກແບຣນດ໌ ແລະ ປະເພດ',
    selectImage: 'ກະລຸນາເລືອກຮູບພາບ',
    updated: 'ອັບເດດສິນຄ້າສຳເລັດ',
    created: 'ສ້າງສິນຄ້າສຳເລັດ',
    stock: 'ສະຕ໋ອກ',
    inStockStatus: 'ມີສະຕ໋ອກ',
    noProducts: 'ບໍ່ພົບສິນຄ້າ.',
    deleteConfirm: (name: string) => `ລຶບ "${name}"?`,
    deleted: 'ລຶບສິນຄ້າສຳເລັດ',
    manageCatalog: 'ຈັດການລາຍການສິນຄ້າ',
    addProductBtn: 'ເພີ່ມສິນຄ້າ',
  },
  order: {
    payment: 'ການຊຳລະ',
    shipping: 'ການຈັດສົ່ງ',
    waiting: 'ລໍຖ້າ',
    processing: 'ກຳລັງດຳເນີນການ',
    shipped: 'ຈັດສົ່ງແລ້ວ',
    delivered: 'ສົ່ງເຖິງແລ້ວ',
    cancelled: 'ຍົກເລີກແລ້ວ',
    paymentComplete: 'ຊຳລະສຳເລັດ',
    awaitingPayment: 'ລໍຖ້າຊຳລະເງິນ',
    paymentFailed: 'ຊຳລະບໍ່ສຳເລັດ',
    paymentImage: 'ຮູບການຊຳລະ',
    noReceipt: 'ບໍ່ມີໃບຮັບເງິນ',
    qrPlaceholder: 'QR ຕົວຢ່າງ',
    allStatuses: 'ທຸກສະຖານະ',
    orderId: 'ລະຫັດຄຳສັ່ງຊື້',
    customer: 'ລູກຄ້າ',
    viewReceipt: 'ເບິ່ງໃບຮັບເງິນ',
    invoice: (id: number) => `ໃບເກັບເງິນ — #${id}`,
    tracking: 'ເລກຕິດຕາມ',
    noReceiptUploaded: 'ຍັງບໍ່ໄດ້ອັບໂຫຼດໃບຮັບເງິນ',
    item: 'ລາຍການ',
    subtotal: 'ລວມຍ່ອຍ',
    noLineItems: 'ບໍ່ມີລາຍການ.',
    printInvoice: 'ພິມໃບເກັບເງິນ',
    statusUpdated: 'ອັບເດດສະຖານະສຳເລັດ',
  },
  admin: {
    dashboard: 'ແຜງສະຫຼຸບ',
    welcome: 'ຍິນດີຕ້ອນຮັບກັບຄືນ, ນີ້ແມ່ນສິ່ງທີ່ເກີດຂຶ້ນ.',
    totalProducts: 'ສິນຄ້າທັງໝົດ',
    totalCategories: 'ປະເພດທັງໝົດ',
    totalCustomers: 'ລູກຄ້າທັງໝົດ',
    totalOrders: 'ຄຳສັ່ງຊື້ທັງໝົດ',
    totalRevenue: 'ລາຍຮັບທັງໝົດ',
    monthlySales: 'ຍອດຂາຍລາຍເດືອນ (ລາຍຮັບ)',
    ordersPerMonth: 'ຄຳສັ່ງຊື້ຕໍ່ເດືອນ',
    salesByCategory: 'ຍອດຂາຍຕາມປະເພດ',
    recentOrders: 'ຄຳສັ່ງຊື້ລ່າສຸດ',
    noMonthlySales: 'ບໍ່ມີຂໍ້ມູນຍອດຂາຍລາຍເດືອນ.',
    noMonthlyOrders: 'ບໍ່ມີຂໍ້ມູນຄຳສັ່ງຊື້ລາຍເດືອນ.',
    noCategorySales: 'ບໍ່ມີຍອດຂາຍຕາມປະເພດ.',
    noRecentOrders: 'ບໍ່ມີຄຳສັ່ງຊື້ລ່າສຸດ.',
    products: 'ສິນຄ້າ',
    categories: 'ປະເພດ',
    brands: 'ແບຣນດ໌',
    suppliers: 'ຜູ້ສະໜອງ',
    customers: 'ລູກຄ້າ',
    users: 'ຜູ້ໃຊ້',
    orders: 'ຄຳສັ່ງຊື້',
    imports: 'ນຳເຂົ້າສິນຄ້າ',
    settings: 'ຕັ້ງຄ່າ',
    total: (n: number) => `${n} ລາຍການ`,
    adminStaff: (n: number) => `${n} ຜູ້ດູແລ ແລະ ພະນັກງານ`,
    addUser: 'ເພີ່ມຜູ້ໃຊ້',
    editUser: 'ແກ້ໄຂຜູ້ໃຊ້',
    addUserTitle: 'ເພີ່ມຜູ້ໃຊ້',
    passwordKeep: 'ລະຫັດຜ່ານ (ປ່ອຍວ່າງເພື່ອຮັກສາເດີມ)',
    role: 'ບົດບາດ',
    noUsers: 'ບໍ່ພົບຜູ້ໃຊ້.',
    passwordRequired: 'ກະລຸນາປ້ອນລະຫັດຜ່ານ',
    userUpdated: 'ອັບເດດຜູ້ໃຊ້ສຳເລັດ',
    userCreated: 'ສ້າງຜູ້ໃຊ້ສຳເລັດ',
    userDeleted: 'ລຶບຜູ້ໃຊ້ສຳເລັດ',
    editCategory: 'ແກ້ໄຂປະເພດ',
    addCategory: 'ເພີ່ມປະເພດ',
    noCategories: 'ບໍ່ພົບປະເພດ.',
    categoryNameRequired: 'ກະລຸນາປ້ອນຊື່ປະເພດ',
    categoryUpdated: 'ອັບເດດປະເພດສຳເລັດ',
    categoryCreated: 'ສ້າງປະເພດສຳເລັດ',
    categoryDeleted: 'ລຶບປະເພດສຳເລັດ',
    editBrand: 'ແກ້ໄຂແບຣນດ໌',
    addBrand: 'ເພີ່ມແບຣນດ໌',
    tagline: 'ຄຳຂວັນ',
    country: 'ປະເທດ',
    logo: 'ໂລໂກ້',
    logoPreview: 'ຕົວຢ່າງໂລໂກ້',
    noBrands: 'ບໍ່ພົບແບຣນດ໌.',
    brandUpdated: 'ອັບເດດແບຣນດ໌ສຳເລັດ',
    brandCreated: 'ສ້າງແບຣນດ໌ສຳເລັດ',
    brandDeleted: 'ລຶບແບຣນດ໌ສຳເລັດ',
    editSupplier: 'ແກ້ໄຂຜູ້ສະໜອງ',
    addSupplier: 'ເພີ່ມຜູ້ສະໜອງ',
    noProductLinked: 'ບໍ່ເຊື່ອມສິນຄ້າ',
    noSuppliers: 'ບໍ່ພົບຜູ້ສະໜອງ.',
    supplierUpdated: 'ອັບເດດຜູ້ສະໜອງສຳເລັດ',
    supplierCreated: 'ສ້າງຜູ້ສະໜອງສຳເລັດ',
    supplierDeleted: 'ລຶບຜູ້ສະໜອງສຳເລັດ',
    searchCustomers: 'ຄົ້ນຫາລູກຄ້າ...',
    noCustomers: 'ບໍ່ພົບລູກຄ້າ.',
    customerDetail: 'ລາຍລະອຽດລູກຄ້າ',
    selectCustomer: 'ເລືອກລູກຄ້າເພື່ອເບິ່ງລາຍລະອຽດ.',
    joined: 'ເຂົ້າຮ່ວມ',
    totalOrdersLabel: 'ຄຳສັ່ງຊື້ທັງໝົດ:',
    totalSpent: 'ຍອດໃຊ້ຈ່າຍທັງໝົດ:',
    updated: 'ອັບເດດ:',
    noOrders: 'ບໍ່ພົບຄຳສັ່ງຊື້.',
    ordersCount: (n: number, m: number) => `${n} ຈາກ ${m}`,
    importStock: 'ນຳເຂົ້າສິນຄ້າ',
    importHint: 'ເພີ່ມສິນຄ້າ ແລະ ຜູ້ສະໜອງຢ່າງໜ້ອຍຫນຶ່ງລາຍການກ່ອນນຳເຂົ້າ.',
    importTitle: 'ນຳເຂົ້າສິນຄ້າ',
    selectProduct: 'ເລືອກສິນຄ້າ',
    selectSupplier: 'ເລືອກຜູ້ສະໜອງ',
    noImports: 'ບໍ່ມີບັນທຶກການນຳເຂົ້າ.',
    recordsTotal: (count: number, value: string) => `${count} ບັນທຶກ · ມູນຄ່າລວມ ${value}`,
    stockImported: 'ນຳເຂົ້າສິນຄ້າສຳເລັດ',
    importDeleted: 'ລຶບບັນທຶກການນຳເຂົ້າສຳເລັດ',
    deleteImportConfirm: (id: number) => `ລຶບບັນທຶກການນຳເຂົ້າ #${id}?`,
    deleteConfirm: (name: string) => `ລຶບ "${name}"?`,
    loadingChart: 'ກຳລັງໂຫຼດແຜນຜັງ…',
    loadingDashboard: 'ກຳລັງໂຫຼດແຜງສະຫຼຸບ…',
    loadingCustomers: 'ກຳລັງໂຫຼດລູກຄ້າ…',
    loadingUsers: 'ກຳລັງໂຫຼດຜູ້ໃຊ້…',
    loadingSuppliers: 'ກຳລັງໂຫຼດຜູ້ສະໜອງ…',
    loadingImports: 'ກຳລັງໂຫຼດການນຳເຂົ້າ…',
    loadingCategories: 'ກຳລັງໂຫຼດປະເພດ…',
    loadingBrands: 'ກຳລັງໂຫຼດແບຣນດ໌…',
    loadingProducts: 'ກຳລັງໂຫຼດສິນຄ້າ…',
    loadingOrders: 'ກຳລັງໂຫຼດຄຳສັ່ງຊື້…',
    id: 'ລະຫັດ',
    ordersShort: 'ຄຳສັ່ງຊື້',
    settingsTitle: 'ຕັ້ງຄ່າຜູ້ດູແລ',
    supplierDeleteFallback: 'ຜູ້ສະໜອງນີ້',
    noOrdersFound: 'ບໍ່ພົບຄຳສັ່ງຊື້.',
    totalLabel: 'ລວມ',
  },
  colors: {
    black: 'ດຳ',
    white: 'ຂາວ',
    red: 'ແດງ',
    blue: 'ຟ້າ',
    green: 'ຂຽວ',
    gray: 'ເທົາ',
  },
  toast: {
    failedLoadShop: 'ໂຫຼດຮ້ານຄ້າບໍ່ສຳເລັດ',
    failedLoadCategories: 'ໂຫຼດປະເພດບໍ່ສຳເລັດ',
    failedLoadCategory: 'ໂຫຼດປະເພດບໍ່ສຳເລັດ',
    failedLoadBrands: 'ໂຫຼດແບຣນດ໌ບໍ່ສຳເລັດ',
    failedLoadProducts: 'ໂຫຼດສິນຄ້າບໍ່ສຳເລັດ',
    failedLoadCart: 'ໂຫຼດກະຕ່າບໍ່ສຳເລັດ',
    failedLoadCheckout: 'ໂຫຼດການຊຳລະບໍ່ສຳເລັດ',
    failedLoadOrders: 'ໂຫຼດຄຳສັ່ງຊື້ບໍ່ສຳເລັດ',
    failedLoadContact: 'ໂຫຼດຂໍ້ມູນຕິດຕໍ່ບໍ່ສຳເລັດ',
    failedLoadDashboard: 'ໂຫຼດແຜງສະຫຼຸບບໍ່ສຳເລັດ',
    failedLoadCustomers: 'ໂຫຼດລູກຄ້າບໍ່ສຳເລັດ',
    failedLoadUsers: 'ໂຫຼດຜູ້ໃຊ້ບໍ່ສຳເລັດ',
    failedLoadSuppliers: 'ໂຫຼດຜູ້ສະໜອງບໍ່ສຳເລັດ',
    failedLoadImports: 'ໂຫຼດການນຳເຂົ້າບໍ່ສຳເລັດ',
    failedPlaceOrder: 'ສັ່ງຊື້ບໍ່ສຳເລັດ',
    failedUploadReceipt: 'ອັບໂຫຼດໃບຮັບເງິນບໍ່ສຳເລັດ',
    failedCancelOrder: 'ຍົກເລີກຄຳສັ່ງຊື້ບໍ່ສຳເລັດ',
    failedUpdatePassword: 'ອັບເດດລະຫັດຜ່ານບໍ່ສຳເລັດ',
    failedSaveProduct: 'ບັນທຶກສິນຄ້າບໍ່ສຳເລັດ',
    failedDeleteProduct: 'ລຶບສິນຄ້າບໍ່ສຳເລັດ',
    failedSaveCategory: 'ບັນທຶກປະເພດບໍ່ສຳເລັດ',
    failedDeleteCategory: 'ລຶບປະເພດບໍ່ສຳເລັດ',
    failedSaveBrand: 'ບັນທຶກແບຣນດ໌ບໍ່ສຳເລັດ',
    failedDeleteBrand: 'ລຶບແບຣນດ໌ບໍ່ສຳເລັດ',
    failedSaveSupplier: 'ບັນທຶກຜູ້ສະໜອງບໍ່ສຳເລັດ',
    failedDeleteSupplier: 'ລຶບຜູ້ສະໜອງບໍ່ສຳເລັດ',
    failedSaveUser: 'ບັນທຶກຜູ້ໃຊ້ບໍ່ສຳເລັດ',
    failedDeleteUser: 'ລຶບຜູ້ໃຊ້ບໍ່ສຳເລັດ',
    failedImportStock: 'ນຳເຂົ້າສິນຄ້າບໍ່ສຳເລັດ',
    failedDeleteImport: 'ລຶບບັນທຶກການນຳເຂົ້າບໍ່ສຳເລັດ',
    failedSendMessage: 'ສົ່ງຂໍ້ຄວາມບໍ່ສຳເລັດ',
    failedLoadOptions: 'ໂຫຼດຕົວເລືອກບໍ່ສຳເລັດ',
    failedUpdateStatus: 'ອັບເດດສະຖານະບໍ່ສຳເລັດ',
    failedLoadProduct: 'ໂຫຼດສິນຄ້າບໍ່ສຳເລັດ',
    invalidOrder: 'ຄຳສັ່ງຊື້ບໍ່ຖືກຕ້ອງ',
    orderNotFound: 'ບໍ່ພົບຄຳສັ່ງຊື້',
  },
  meta: {
    title: 'SportShop — ອຸປະກອນກິລາຄຸນນະພາບ',
    description:
      'ອຸປະກອນກິລາແທ້ຈາກ Nike, Adidas, Puma ແລະ ອື່ນໆ. ຮອງເທົ້າ, ເສື້ອຜ້າກິລາ ແລະ ອຸປະກອນອอกกำลัง.',
  },
} as const;

/** Map shipping/payment status to Lao label */
export function statusLabel(status: string | null | undefined): string {
  if (!status) return lo.common.na;
  const key = status.toLowerCase().trim();
  const map: Record<string, string> = {
    waiting: lo.order.waiting,
    processing: lo.order.processing,
    shipped: lo.order.shipped,
    delivered: lo.order.delivered,
    cancelled: lo.order.cancelled,
    canceled: lo.order.cancelled,
    active: lo.common.active,
    inactive: lo.common.inactive,
    admin: lo.common.admin,
    staff: lo.common.staff,
    customer: 'ລູກຄ້າ',
    pending: lo.order.awaitingPayment,
    paid: lo.order.paymentComplete,
    verified: lo.order.paymentComplete,
    approved: lo.order.paymentComplete,
    rejected: lo.order.paymentFailed,
    failed: lo.order.paymentFailed,
  };
  return map[key] ?? status;
}
